# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10d30025b7ac56a809bbcffbaa46a89e802a9f82dd9232afafdf248c0271de34e5a120414bc11e1059864bd799b0651acce6a6d016e11fa7c18a68f6261316ef

test:
  secret_key_base: 78352e22209704ab7c0bea92ea88e0fb188f76d283f85aa0379746255291435f20addfeb855f1ffee6619a25dbabc62a562edbf554546f99599cf7ad99077716

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
